############################测试pagehelper#################################
#服务端口
server:
  port: 56081
#服务名
spring:
  application:
    name: sharding-jdbc-examples
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://192.168.87.133:3306/order_db?useUnicode=true
      driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

#日志打印
logging:
  level:
    root: info
    org.springframework.web: info
    com.lucifer.sharding.dao: debug
    druid.sql: debug

pagehelper:
  reasonable: false # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql
